In [116]:
# Initialize arrays X, y, weights at both layers and bias at both layers
import numpy as np
# X = np.array([(1, 0, 1,0), (1, 0, 1,1), (0, 1, 0, 1),])
X = np.round(np.random.random((3, 4)), 2)

y = np.array ([(1,), (1,), (0,)])

# Initialize weights and bias
# w_one = np.array([(0.42, 0.88, 0.55), (0.10, 0.73, 0.68), (0.60, 0.18, 0.47), (0.92, 0.11, 0.52)])
# b_one = np.array([(0.46, 0.72, 0.08)])

# w_two = np.array([(0.30,), (0.25,), (0.23,)])
# b_two = np.array([(0.69,)])

w_one = np.round(np.random.random((4, 3)), 2)
b_one = np.round(np.random.random((1, 3)), 2)

w_two = np.round(np.random.random((3, 1)), 2)
b_two = np.round(np.random.random((1, 1)), 2)

print ('Shape of X is ', X.shape)
print ('Shape of y is ', y.shape)
print('Shape of w_one is ', w_one.shape)
print('Shape of b_one is ', b_one.shape)
print('Shape of w_two is ', w_two.shape)
print('Shape of b_two is ', b_two.shape)

print ('Contents of array X is  ', X)
print ('Contents of array y is  ', y)
print ('Contents of w_one is ', w_one)
print ('Contents of b_one is ', b_one)
print ('Contents of w_two is ', w_two)
print ('Contents of b_two is ', b_two)

Shape of X is  (3, 4)
Shape of y is  (3, 1)
Shape of w_one is  (4, 3)
Shape of b_one is  (1, 3)
Shape of w_two is  (3, 1)
Shape of b_two is  (1, 1)
Contents of array X is   [[0.95 0.54 0.23 0.49]
 [0.65 0.83 0.55 0.24]
 [0.63 0.47 0.94 0.63]]
Contents of array y is   [[1]
 [1]
 [0]]
Contents of w_one is  [[0.98 0.61 0.77]
 [0.62 0.1  0.94]
 [0.31 0.74 0.38]
 [0.97 0.29 0.92]]
Contents of b_one is  [[0.4  0.57 0.48]]
Contents of w_two is  [[0.18]
 [0.54]
 [0.12]]
Contents of b_two is  [[0.54]]


In [121]:
#Calculate hidden layer input
z_one = np.dot(X, w_one) + b_one
print ('Hidden layer input is ', z_one)

Hidden layer input is  [[2.2124 1.5158 2.2573]
 [1.9549 1.5261 2.1905]
 [2.2113 1.8796 2.3437]]


In [122]:
#define sigmoid function that will be used to calculate activations
def sigmoid(z):
    a = 1/(1+np.exp(-z))
    return (np.round(a, 2))

In [123]:
#Calculate hidden layer activations
a_one = sigmoid(z_one)
print('Hidden layer activations are ', a_one)

Hidden layer activations are  [[0.9  0.82 0.91]
 [0.88 0.82 0.9 ]
 [0.9  0.87 0.91]]


In [124]:
#Calculate output layer's input and activations
z_two = np.dot(a_one, w_two) + b_two
a_two = sigmoid(z_two)
print ('Output layer activations are ', a_two)

Output layer activations are  [[0.78]
 [0.78]
 [0.78]]


In [125]:
# Calculate error at output layer
error_two = y - a_two
print ('Error at the output layer is ', error_two)

Error at the output layer is  [[ 0.22]
 [ 0.22]
 [-0.78]]


In [126]:
# define the derivative function for sigmoid
def derivative_sigmoid(a):
    da = a * (1 - a)
    return (np.round(da, 2))

In [127]:
# Compute slope at output and hidden layer
da_two = derivative_sigmoid(a_two)
print ('Slope of output is', da_two)

da_one = derivative_sigmoid(a_one)
print ('Slope of hidden layer is', da_one)

Slope of output is [[0.17]
 [0.17]
 [0.17]]
Slope of hidden layer is [[0.09 0.15 0.08]
 [0.11 0.15 0.09]
 [0.09 0.11 0.08]]


In [128]:
# Calculate d_output
d_two = np.round(np.multiply(error_two, da_two), 2)
print ('Delta output is ', d_two)

Delta output is  [[ 0.04]
 [ 0.04]
 [-0.13]]


In [129]:
# Error at hidden layer
error_one = np.round(np.dot(d_two, w_two.T), 3)
print ('Error at hidden layer is ', error_one)

Error at hidden layer is  [[ 0.007  0.022  0.005]
 [ 0.007  0.022  0.005]
 [-0.023 -0.07  -0.016]]


In [130]:
# Compute delta at hidden layer
d_one = np.round(np.multiply(error_one, da_one), 3)
print ('Delta at hidden layer is ', d_one)

Delta at hidden layer is  [[ 0.001  0.003  0.   ]
 [ 0.001  0.003  0.   ]
 [-0.002 -0.008 -0.001]]


In [131]:
# Update weight at both output and hidden layer
learning_rate = 0.1
w_two = w_two + np.dot(a_one.T, d_two) * learning_rate
w_two = np.round(w_two, 4)
w_one = w_one + np.dot(X.T, d_one) * learning_rate
w_one = np.round(w_one, 4)

print ('Updated weights at the output layer is ', w_two)
print ('Updated weights at the hidden layer is ', w_one)

Updated weights at the output layer is  [[0.1754]
 [0.5352]
 [0.1154]]
Updated weights at the hidden layer is  [[0.98   0.61   0.7699]
 [0.62   0.1    0.94  ]
 [0.3099 0.7395 0.3799]
 [0.9699 0.2897 0.9199]]


In [132]:
# Update biases at both output and hidden layer
b_one = b_one + np.sum(d_one, axis=0) * learning_rate
b_two = b_two + np.sum(d_two, axis=0) * learning_rate

print ('Updated bias at the output layer is ', b_one)
print ('Updated bias at the hidden layer is ', b_two)

Updated bias at the output layer is  [[0.4    0.5698 0.4799]]
Updated bias at the hidden layer is  [[0.535]]
